pipeline{
    agent any
    stages{
        stage ('code checkout'){
            steps{
                git branch: 'main', url: 'https://github.com/vintijain/project.git'
            }
        }
        stage ('list file'){
            stpes{
                sh 'ls -la'
            }
        }
    }
}

------------------------------------
//mvn lifecycle  -  validate → compile → test → package → install
//mvn install do everything in one command

pipeline{
    agent any
    tools {
        maven 'Maven-3.8.1'
        jdk 'JDK-17'
    }
    stages{
        stage('Checkout'){
            steps{
                git url: https://github.com/vintijain/project-java.git
            }
        }

        stage('Compile'){
            steps{
                sh 'mvn clean compile'
            }
        }

        stage('Test'){
            steps{
                sh 'mvn test'
            }
        }

        stage('Package'){
            steps{
                sh 'mvn package'
            }
        }
    }
}