pipeline{
    agent any
    stages{
        stage ('code checkout'){
            steps{
                git branch: 'main', url: 'https://github.com/vintijain/project.git'
            }
        }
        stage ('list file'){
            stpes{
                sh 'ls -la'
            }
        }
    }
}

//--------------------------------------------------------------------------------
//mvn lifecycle  -  validate → compile → test → package → install
//mvn install do everything in one command

pipeline{
    agent any
    tools {
        maven 'Maven-3.8.1'
        jdk 'JDK-17'
    }
    stages{
        stage('Checkout'){
            steps{
                git url: 'https://github.com/vintijain/project-java.git'
            }
        }

        stage('Compile'){
            steps{
                sh 'mvn clean compile'
            }
        }

        stage('Test'){
            steps{
                sh 'mvn test'
            }
        }

        stage('Package'){
            steps{
                sh 'mvn package'
            }
        }
    }
}


//-------------------------------------------------------------

pipeline {
    agent any
    tools {
        nodejs 'NodeJS-16'
    }
    environment {
        VERSION = "1.2"
    }
    parameters {
        string(name: 'ENVIRONMENT', defaultValue: 'dev', description: 'Deployment Environment')
    }
    stages{
        stage ('checkout')
        {
            steps{
                git url: 'https://github.com/jainvinti/project-nodejs.git'
            }
        }

        stage ('install dependecies'){
            steps {
                sh 'npm install'
                sh 'echo "$VERSION"' 
                sh 'echo "Deploying to $ENVIRONMENT"'
            }
        }

        stage('run tests'){
            steps{
                sh 'npm test'
            }
        }

        stage('Build'){
            steps{
                sh 'npm run build'
            }
        }

        stage('Deploy'){
            when {
                expression { params.ENVIRONMENT == 'dev' }
            }
            steps {
                sh 'echo deploying version $VERSION on $ENVIRONMENT'
            }
        }

        stage('Artifacts'){
            steps{
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }
    }
}

//-------------------------------------------------------------
//parallel stages
pipeline{
    agent any
    stages{
        parallel{
            stage('build'){
                steps{
                    sh 'mvn clean compile'
                }
            }
            stage('test'){
                steps{
                    sh 'mvn test'
                }
            }
        }
    }
}